### ISSUE TITLE
cannot find symbol

### ISSUE THREAD

**Issue by luandro** [aboozaid/react-native-wifi-hotspot#10]
Seems related to #6, but the suggested fixes don't seem to work with latest react-native 0.61.2.

```
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/home/app/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:78: error: cannot find symbol
      new HotspotModule()
          ^
  symbol:   class HotspotModule
  location: class PackageList
1 error
```
Tried adding package manually to MainApplication.java without success:

```
@Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      packages.add(new HotspotPackage());
      return packages;
    }
```

Any suggestions?

**Comment by aboozaid** [comment]
did you import the package name at the top of MainApplication.java before adding it to packages?!

**Comment by luandro** [comment]
Yup @assemmohamedali!

**Comment by aboozaid** [comment]
I don't think you add it correctly, could you please re-try? read this as well https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

**Comment by luandro** [comment]
Got it to work! :tada:

Disabled autolinking as documented [here](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library).

Details on manually adding it can be found [here](https://github.com/luandro/huiom/commit/c5f3dd22c9ebae805e09de6c45660fc415569e9f).

**Comment by Patrick-Erichsen** [comment]
This worked for me as well running react-native 0.61.5, thanks!
